baseURL = "http://kayan.my.to/"
languageCode = "en-us"
title = "Kayan"
theme = "hyde"
enableEmoji = true

[params]
  description = 'A simple personal blog with the adventures of a developer born in Rio.'
  layoutReverse = true

[[menu.main]]
    name = "posts"
    weight = 1
    url = "/posts/"

[[menu.main]]
    name = "random"
    weight = 2
    url = "/random/"

[[menu.main]]
    identifier = "git"
    post = "<i class='fa fa-github'></i>"
    weight = 100
    url = "http://github.com/ktalmeida"
